try fix travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -74,10 +74,10 @@ script:
   # Run the tests
   # Also, put the output in a log so we can analyze it afterwards
   # Also, do not exit yet if tests fail, we want to post the results to slack
-  - ./google-cloud-sdk/bin/gcloud firebase test android run 
-    --type instrumentation 
-    --app $TRAVIS_BUILD_DIR/app/build/outputs/apk/debug/app-debug.apk 
-    --test $TRAVIS_BUILD_DIR/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk 
+  - ./google-cloud-sdk/bin/gcloud firebase test android run \
+    --type instrumentation \
+    --app $TRAVIS_BUILD_DIR/app/build/outputs/apk/debug/app-debug.apk \
+    --test $TRAVIS_BUILD_DIR/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
     --device model=Pixel2,version=28,locale=en,orientation=portrait > firebase-androidTest-run.log || true
 
   # print the testing logs afterwards (to not hide it from the log on Travis)
@@ -88,10 +88,10 @@ script:
 
   # If the table contains "Failed"
   - if [[ $test_result_table == *"Failed"* ]]; then
-  # androidTest run failed! Post some info to Slack
-  echo "androidTest have failed, sending Slack notification"
-  curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Firebase TestLab results\nTravis build ${TRAVIS_BRANCH}\n \`\`\`${test_result_table}\`\`\`\"}" https://hooks.slack.com/services/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
-  # Make the build fail
-  exit 1
-  fi
+      # androidTest run failed! Post some info to Slack
+      echo "androidTest have failed, sending Slack notification"
+      curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Firebase TestLab results\nTravis build ${TRAVIS_BRANCH}\n \`\`\`${test_result_table}\`\`\`\"}" https://hooks.slack.com/services/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
+      # Make the build fail
+      exit 1;
+    fi
 
